from __future__ import annotations

import copy
import random
from typing import Dict, List


class TicketBank:
    """Deterministic bank of realistic support ticket scenarios."""

    def __init__(self) -> None:
        self._tickets: List[Dict] = [
            {
                "ticket_id": "TKT-001",
                "ticket_text": "I was charged twice for my April subscription even though I only have one workspace. The second charge showed up on my card this morning and I need it reversed. Please confirm which invoice is valid.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.28,
                "customer_tier": "premium",
                "resolution_keywords": ["refund", "invoice", "charge", "review"],
                "correct_response_hint": "Acknowledge the duplicate charge, mention reviewing the invoice, and explain the refund timeline.",
            },
            {
                "ticket_id": "TKT-002",
                "ticket_text": "I cannot reset my password because the reset email never arrives. I checked spam and tried twice from two browsers. Can you help me get back into my account today?",
                "correct_department": "technical",
                "requires_escalation": False,
                "base_sentiment": 0.34,
                "customer_tier": "free",
                "resolution_keywords": ["reset", "email", "link", "account"],
                "correct_response_hint": "Offer password reset troubleshooting, mention verifying the email address, and confirm next recovery steps.",
            },
            {
                "ticket_id": "TKT-003",
                "ticket_text": "Our team would love a bulk archive feature for closed cases. Right now we have to archive them one by one, which is slow. Is this on your roadmap or is there another way to do it?",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.76,
                "customer_tier": "premium",
                "resolution_keywords": ["feature", "request", "roadmap", "feedback"],
                "correct_response_hint": "Thank them for the feature request, say it will be shared with product, and explain any current workaround.",
            },
            {
                "ticket_id": "TKT-004",
                "ticket_text": "I canceled during the trial but I still see a pending charge on my bank statement. I need to know whether this will settle or disappear. This is confusing and I do not want to be billed after canceling.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.22,
                "customer_tier": "free",
                "resolution_keywords": ["cancel", "charge", "billing", "statement"],
                "correct_response_hint": "Clarify the cancellation status, explain pending authorization behavior, and confirm billing will be reviewed.",
            },
            {
                "ticket_id": "TKT-005",
                "ticket_text": "The dashboard loads but every chart is blank after I apply a date filter. My teammate sees the same thing on Chrome and Safari. We need this fixed before our weekly review.",
                "correct_department": "technical",
                "requires_escalation": False,
                "base_sentiment": 0.31,
                "customer_tier": "premium",
                "resolution_keywords": ["bug", "dashboard", "filter", "fix"],
                "correct_response_hint": "Acknowledge the reproducible bug, mention investigating the dashboard filter issue, and set expectations for a fix or workaround.",
            },
            {
                "ticket_id": "TKT-006",
                "ticket_text": "My account was locked after a few failed sign-in attempts, but now the unlock link says it expired. I have client calls in an hour and need urgent access. What can be done right away?",
                "correct_department": "technical",
                "requires_escalation": True,
                "base_sentiment": 0.18,
                "customer_tier": "premium",
                "resolution_keywords": ["unlock", "access", "link", "urgent"],
                "correct_response_hint": "Address the urgency, explain the account unlock process, and offer immediate access recovery steps.",
            },
            {
                "ticket_id": "TKT-007",
                "ticket_text": "We are thinking about moving from Premium to Enterprise, but I cannot tell what the audit log retention limits are. Could someone explain the upgrade differences in plain language? We need to decide this week.",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.68,
                "customer_tier": "premium",
                "resolution_keywords": ["upgrade", "enterprise", "plan", "features"],
                "correct_response_hint": "Explain the upgrade path, mention Enterprise plan capabilities, and offer follow-up help.",
            },
            {
                "ticket_id": "TKT-008",
                "ticket_text": "Please cancel our subscription at the end of the current billing cycle. We do not want an immediate shutdown because accounting still needs to export records. Confirm there will be no renewal charge.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.47,
                "customer_tier": "premium",
                "resolution_keywords": ["cancel", "renewal", "billing", "confirm"],
                "correct_response_hint": "Confirm the cancellation timing, mention the renewal status, and reassure the customer about billing.",
            },
            {
                "ticket_id": "TKT-009",
                "ticket_text": "I need a full export of our ticket history for compliance review. I found the CSV export for single views, but not the complete account export. Where exactly can I request that?",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.61,
                "customer_tier": "free",
                "resolution_keywords": ["export", "data", "history", "request"],
                "correct_response_hint": "Point them to the data export process and mention what export scope is supported.",
            },
            {
                "ticket_id": "TKT-010",
                "ticket_text": "Your SLA says Premium support gets a first response within 24 hours, but this ticket has been open for two days. I have written three times already. This kind of delay is making us reconsider renewal.",
                "correct_department": "general",
                "requires_escalation": True,
                "base_sentiment": 0.12,
                "customer_tier": "premium",
                "resolution_keywords": ["sla", "response", "delay", "priority"],
                "correct_response_hint": "Apologize for the SLA miss, acknowledge prior contacts, and explain the priority follow-up plan.",
            },
            {
                "ticket_id": "TKT-011",
                "ticket_text": "Our Salesforce integration stopped syncing new contacts after yesterday's maintenance window. Historical records are still there, but nothing new is coming through. Can technical support check whether the connector is failing?",
                "correct_department": "technical",
                "requires_escalation": True,
                "base_sentiment": 0.26,
                "customer_tier": "enterprise",
                "resolution_keywords": ["integration", "sync", "connector", "technical"],
                "correct_response_hint": "Acknowledge the integration incident, mention sync diagnostics, and outline immediate technical investigation steps.",
            },
            {
                "ticket_id": "TKT-012",
                "ticket_text": "Invoice 8842 shows ten seats, but we only have eight active users. I need a corrected invoice before finance closes the month. Please review the seat count and fix the billing error.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.29,
                "customer_tier": "enterprise",
                "resolution_keywords": ["invoice", "seats", "billing", "corrected"],
                "correct_response_hint": "Confirm the invoice discrepancy, mention seat review, and commit to issuing a corrected billing statement.",
            },
            {
                "ticket_id": "TKT-013",
                "ticket_text": "Is there a platform outage right now? None of our agents can load the inbox and the API health check is timing out. We have customers waiting and need an update immediately.",
                "correct_department": "technical",
                "requires_escalation": True,
                "base_sentiment": 0.08,
                "customer_tier": "enterprise",
                "resolution_keywords": ["outage", "status", "investigating", "update"],
                "correct_response_hint": "Acknowledge the outage symptoms, say the issue is being investigated, and promise status updates.",
            },
            {
                "ticket_id": "TKT-014",
                "ticket_text": "We just signed up and I am trying to understand the best way to onboard new agents. The help center is broad, and I am not sure which setup steps matter first. Can you point me in the right direction?",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.82,
                "customer_tier": "free",
                "resolution_keywords": ["onboarding", "setup", "guide", "steps"],
                "correct_response_hint": "Share onboarding guidance, highlight the first setup steps, and point them to relevant documentation or help.",
            },
            {
                "ticket_id": "TKT-015",
                "ticket_text": "I changed plans last month and now the billing page shows both 'Starter' and 'Premium' labels. I do not know which subscription is active or what I am actually paying for. Please explain the current plan clearly.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.41,
                "customer_tier": "premium",
                "resolution_keywords": ["subscription", "plan", "billing", "clarify"],
                "correct_response_hint": "Clarify the active subscription, mention plan history if relevant, and explain the billing view.",
            },
            {
                "ticket_id": "TKT-016",
                "ticket_text": "I requested a refund last week after downgrading, but I have not heard back. The unused annual amount is significant and I need an answer before Friday. Please tell me the status.",
                "correct_department": "billing",
                "requires_escalation": True,
                "base_sentiment": 0.17,
                "customer_tier": "enterprise",
                "resolution_keywords": ["refund", "status", "annual", "review"],
                "correct_response_hint": "Acknowledge the delayed refund review, reference the unused annual amount, and explain the next billing action.",
            },
            {
                "ticket_id": "TKT-017",
                "ticket_text": "Our SSO login is looping back to the sign-in page after authentication. Multiple admins reproduced it and we are locked out of admin settings. This is blocking work across two regions.",
                "correct_department": "technical",
                "requires_escalation": True,
                "base_sentiment": 0.11,
                "customer_tier": "enterprise",
                "resolution_keywords": ["sso", "login", "authentication", "investigate"],
                "correct_response_hint": "Recognize the SSO failure, mention authentication investigation, and prioritize restoring access.",
            },
            {
                "ticket_id": "TKT-018",
                "ticket_text": "Can I export usage metrics into Google Sheets automatically? I did not see a native connector, but if there is an API recipe or Zapier path that works, that would help.",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.71,
                "customer_tier": "free",
                "resolution_keywords": ["export", "api", "integration", "guide"],
                "correct_response_hint": "Explain the available export or integration options and give a clear next step.",
            },
            {
                "ticket_id": "TKT-019",
                "ticket_text": "The latest invoice includes VAT even though our account has a validated tax exemption certificate on file. Finance rejected the payment until this is corrected. Can billing update the invoice today?",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.25,
                "customer_tier": "enterprise",
                "resolution_keywords": ["invoice", "tax", "vat", "correct"],
                "correct_response_hint": "Confirm the tax issue, mention reviewing the exemption certificate, and explain invoice correction steps.",
            },
            {
                "ticket_id": "TKT-020",
                "ticket_text": "The mobile app crashes every time I attach a screenshot to a reply. I updated to the newest version this morning and it still happens. Please advise before I ask my team to roll back.",
                "correct_department": "technical",
                "requires_escalation": False,
                "base_sentiment": 0.33,
                "customer_tier": "premium",
                "resolution_keywords": ["crash", "app", "screenshot", "fix"],
                "correct_response_hint": "Acknowledge the crash report, mention investigating the attachment flow, and suggest any safe workaround.",
            },
            {
                "ticket_id": "TKT-021",
                "ticket_text": "We need help understanding how to set up queues and assignment rules for our first week on the platform. The documentation assumes we already know the terminology. Can someone walk us through the basics?",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.79,
                "customer_tier": "premium",
                "resolution_keywords": ["queues", "assignment", "setup", "guide"],
                "correct_response_hint": "Offer onboarding help, explain queues and assignment setup, and point them to the right guide.",
            },
            {
                "ticket_id": "TKT-022",
                "ticket_text": "I downgraded from annual to monthly, but the portal still says my renewal is next year. I do not want to be surprised by a large renewal invoice. Please confirm how the downgrade will bill going forward.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.39,
                "customer_tier": "premium",
                "resolution_keywords": ["downgrade", "renewal", "invoice", "billing"],
                "correct_response_hint": "Clarify the downgrade billing schedule and reassure them about future renewal behavior.",
            },
            {
                "ticket_id": "TKT-023",
                "ticket_text": "Webhook deliveries have been timing out for one of our production endpoints since noon UTC. Retries are piling up and some order confirmations are delayed. We need engineering eyes on this quickly.",
                "correct_department": "technical",
                "requires_escalation": True,
                "base_sentiment": 0.14,
                "customer_tier": "enterprise",
                "resolution_keywords": ["webhook", "timeout", "retries", "engineering"],
                "correct_response_hint": "Acknowledge the production impact, mention timeout investigation, and explain the engineering escalation path.",
            },
            {
                "ticket_id": "TKT-024",
                "ticket_text": "I have a general question: does the free plan include unlimited teammates or is there a cap? I checked the pricing page and still was not sure. A simple answer is fine.",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.88,
                "customer_tier": "free",
                "resolution_keywords": ["plan", "free", "pricing", "teammates"],
                "correct_response_hint": "Answer the plan question directly and explain where to verify teammate limits.",
            },
            {
                "ticket_id": "TKT-025",
                "ticket_text": "My card was declined, but when I updated the payment method the system still suspended our workspace. Billing should have retried automatically according to your help article. Please restore service and explain what happened.",
                "correct_department": "billing",
                "requires_escalation": True,
                "base_sentiment": 0.19,
                "customer_tier": "premium",
                "resolution_keywords": ["payment", "billing", "restore", "retry"],
                "correct_response_hint": "Acknowledge the suspension, mention the payment retry review, and explain restoration steps.",
            },
            {
                "ticket_id": "TKT-026",
                "ticket_text": "Search stopped returning older closed tickets after the new release. We rely on historical search for audits, and now results cut off after thirty days. Is this a bug or a changed setting?",
                "correct_department": "technical",
                "requires_escalation": False,
                "base_sentiment": 0.27,
                "customer_tier": "premium",
                "resolution_keywords": ["search", "bug", "results", "audit"],
                "correct_response_hint": "Acknowledge the search issue, mention reviewing the release change, and describe the next technical step.",
            },
            {
                "ticket_id": "TKT-027",
                "ticket_text": "Our procurement team needs a formal quote for Enterprise before they can approve the upgrade. I am not reporting a bug; I just need the right sales or support path. Who handles that request?",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.73,
                "customer_tier": "premium",
                "resolution_keywords": ["quote", "enterprise", "upgrade", "request"],
                "correct_response_hint": "Route them to the right commercial path, mention the quote request, and explain what information to provide.",
            },
            {
                "ticket_id": "TKT-028",
                "ticket_text": "I canceled yesterday, but the account still shows 'active' and I can still create tickets. I am worried the cancellation did not save. Please verify the subscription status and billing state.",
                "correct_department": "billing",
                "requires_escalation": False,
                "base_sentiment": 0.36,
                "customer_tier": "free",
                "resolution_keywords": ["cancel", "status", "subscription", "verify"],
                "correct_response_hint": "Verify the cancellation request and explain the current subscription and billing status.",
            },
            {
                "ticket_id": "TKT-029",
                "ticket_text": "The API is returning 401 for valid service tokens after we rotated secrets. We already updated the header format according to docs, so something deeper seems off. Can technical support review authentication logs?",
                "correct_department": "technical",
                "requires_escalation": True,
                "base_sentiment": 0.16,
                "customer_tier": "enterprise",
                "resolution_keywords": ["api", "401", "tokens", "logs"],
                "correct_response_hint": "Acknowledge the authentication failure, mention reviewing logs, and explain the next debugging step.",
            },
            {
                "ticket_id": "TKT-030",
                "ticket_text": "I want to know whether your system supports exporting attachments along with ticket metadata. We are preparing for an internal archive and need to scope the effort. Documentation links would be helpful.",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.67,
                "customer_tier": "premium",
                "resolution_keywords": ["export", "attachments", "metadata", "documentation"],
                "correct_response_hint": "Explain attachment export support and provide documentation-oriented next steps.",
            },
            {
                "ticket_id": "TKT-031",
                "ticket_text": "Our monthly bill jumped by almost 40 percent with no warning. I need an itemized explanation of the new charges, and if this is an error it must be fixed before payment is due tomorrow. This is not acceptable for an enterprise account.",
                "correct_department": "billing",
                "requires_escalation": True,
                "base_sentiment": 0.09,
                "customer_tier": "enterprise",
                "resolution_keywords": ["itemized", "charges", "billing", "review"],
                "correct_response_hint": "Acknowledge the billing spike, offer an itemized review, and communicate urgency around payment timing.",
            },
            {
                "ticket_id": "TKT-032",
                "ticket_text": "I imported our knowledge base, but all article formatting is stripped out in the published help center. Headings and code blocks are flattened into plain text. Is there a migration setting we missed?",
                "correct_department": "technical",
                "requires_escalation": False,
                "base_sentiment": 0.38,
                "customer_tier": "premium",
                "resolution_keywords": ["import", "formatting", "migration", "technical"],
                "correct_response_hint": "Acknowledge the import issue, mention migration or formatting checks, and outline a technical workaround or investigation.",
            },
            {
                "ticket_id": "TKT-033",
                "ticket_text": "Can someone explain the difference between archived and deleted conversations? We are updating our retention policy and do not want to make a mistake. A concise answer is okay.",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.84,
                "customer_tier": "free",
                "resolution_keywords": ["archived", "deleted", "retention", "difference"],
                "correct_response_hint": "Explain the distinction clearly and help the customer understand retention implications.",
            },
            {
                "ticket_id": "TKT-034",
                "ticket_text": "Our admins have opened four tickets this week about delayed responses, and nobody has taken ownership. We are paying for Enterprise support and still getting silence. Escalate this to someone who can actually help.",
                "correct_department": "general",
                "requires_escalation": True,
                "base_sentiment": 0.05,
                "customer_tier": "enterprise",
                "resolution_keywords": ["escalate", "ownership", "enterprise", "support"],
                "correct_response_hint": "Acknowledge the repeated support failure, take ownership, and confirm immediate escalation.",
            },
            {
                "ticket_id": "TKT-035",
                "ticket_text": "I am trying to connect Slack notifications, but test messages never arrive in the selected channel. The OAuth flow completed successfully, so I am not sure what is missing. Can you help me troubleshoot the integration?",
                "correct_department": "technical",
                "requires_escalation": False,
                "base_sentiment": 0.52,
                "customer_tier": "free",
                "resolution_keywords": ["slack", "integration", "notifications", "troubleshoot"],
                "correct_response_hint": "Acknowledge the Slack integration issue and provide practical troubleshooting steps.",
            },
            {
                "ticket_id": "TKT-036",
                "ticket_text": "We need to export all customer conversations before ending our contract next month. I also want confirmation that canceling will not delete data before the export completes. Please outline the safest sequence.",
                "correct_department": "general",
                "requires_escalation": False,
                "base_sentiment": 0.58,
                "customer_tier": "premium",
                "resolution_keywords": ["export", "cancel", "data", "sequence"],
                "correct_response_hint": "Explain the export-before-cancellation sequence and reassure them about data retention during the process.",
            },
        ]
        self._task_pools = {
            "easy": {
                "TKT-001",
                "TKT-002",
                "TKT-003",
                "TKT-004",
                "TKT-005",
                "TKT-007",
                "TKT-008",
                "TKT-009",
                "TKT-014",
                "TKT-015",
                "TKT-018",
                "TKT-020",
                "TKT-021",
                "TKT-022",
                "TKT-024",
                "TKT-026",
                "TKT-027",
                "TKT-028",
                "TKT-030",
                "TKT-033",
                "TKT-035",
                "TKT-036",
            },
            "medium": {
                "TKT-001",
                "TKT-002",
                "TKT-003",
                "TKT-004",
                "TKT-005",
                "TKT-007",
                "TKT-008",
                "TKT-009",
                "TKT-012",
                "TKT-014",
                "TKT-015",
                "TKT-018",
                "TKT-019",
                "TKT-020",
                "TKT-021",
                "TKT-022",
                "TKT-024",
                "TKT-026",
                "TKT-027",
                "TKT-028",
                "TKT-030",
                "TKT-032",
                "TKT-033",
                "TKT-035",
                "TKT-036",
            },
        }

    def get_tickets(self, seed: int, task_name: str) -> List[Dict]:
        task_key = task_name.lower()
        if task_key in self._task_pools:
            eligible = [ticket for ticket in self._tickets if ticket["ticket_id"] in self._task_pools[task_key]]
        else:
            eligible = list(self._tickets)

        shuffled = copy.deepcopy(eligible)
        task_offset = {"easy": 11, "medium": 23, "hard": 37}.get(task_key, 0)
        random.Random(seed + task_offset).shuffle(shuffled)
        return shuffled
